<?php

return [
    [
        'id' => 1,
        'short_name' => 'AD',
        'name' => 'Andorra',
        'phonecode' => '376',
        'is_eu_member' => false,
    ],
    [
        'id' => 2,
        'short_name' => 'AE',
        'name' => 'United Arab Emirates',
        'phonecode' => '971',
        'is_eu_member' => false,
    ],
    [
        'id' => 3,
        'short_name' => 'AF',
        'name' => 'Afghanistan',
        'phonecode' => '93',
        'is_eu_member' => false,
    ],
    [
        'id' => 4,
        'short_name' => 'AG',
        'name' => 'Antigua and Barbuda',
        'phonecode' => '1-268',
        'is_eu_member' => false,
    ],
    [
        'id' => 5,
        'short_name' => 'AI',
        'name' => 'Anguilla',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 6,
        'short_name' => 'AL',
        'name' => 'Albania',
        'phonecode' => '355',
        'is_eu_member' => false,
    ],
    [
        'id' => 7,
        'short_name' => 'AM',
        'name' => 'Armenia',
        'phonecode' => '374',
        'is_eu_member' => false,
    ],
    [
        'id' => 8,
        'short_name' => 'AO',
        'name' => 'Angola',
        'phonecode' => '244',
        'is_eu_member' => false,
    ],
    [
        'id' => 9,
        'short_name' => 'AQ',
        'name' => 'Antarctica',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 10,
        'short_name' => 'AR',
        'name' => 'Argentina',
        'phonecode' => '54',
        'is_eu_member' => false,
    ],
    [
        'id' => 11,
        'short_name' => 'AS',
        'name' => 'American Samoa',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 12,
        'short_name' => 'AT',
        'name' => 'Austria',
        'phonecode' => '43',
        'is_eu_member' => true,
    ],
    [
        'id' => 13,
        'short_name' => 'AU',
        'name' => 'Australia',
        'phonecode' => '61',
        'is_eu_member' => false,
    ],
    [
        'id' => 14,
        'short_name' => 'AW',
        'name' => 'Aruba',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 15,
        'short_name' => 'AX',
        'name' => 'Åland Islands',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 16,
        'short_name' => 'AZ',
        'name' => 'Azerbaijan',
        'phonecode' => '994',
        'is_eu_member' => false,
    ],
    [
        'id' => 17,
        'short_name' => 'BA',
        'name' => 'Bosnia and Herzegovina',
        'phonecode' => '387',
        'is_eu_member' => false,
    ],
    [
        'id' => 18,
        'short_name' => 'BB',
        'name' => 'Barbados',
        'phonecode' => '1-246',
        'is_eu_member' => false,
    ],
    [
        'id' => 19,
        'short_name' => 'BD',
        'name' => 'Bangladesh',
        'phonecode' => '880',
        'is_eu_member' => false,
    ],
    [
        'id' => 20,
        'short_name' => 'BE',
        'name' => 'Belgium',
        'phonecode' => '32',
        'is_eu_member' => true,
    ],
    [
        'id' => 21,
        'short_name' => 'BF',
        'name' => 'Burkina Faso',
        'phonecode' => '226',
        'is_eu_member' => false,
    ],
    [
        'id' => 22,
        'short_name' => 'BG',
        'name' => 'Bulgaria',
        'phonecode' => '359',
        'is_eu_member' => true,
    ],
    [
        'id' => 23,
        'short_name' => 'BH',
        'name' => 'Bahrain',
        'phonecode' => '973',
        'is_eu_member' => false,
    ],
    [
        'id' => 24,
        'short_name' => 'BI',
        'name' => 'Burundi',
        'phonecode' => '257',
        'is_eu_member' => false,
    ],
    [
        'id' => 25,
        'short_name' => 'BJ',
        'name' => 'Benin',
        'phonecode' => '229',
        'is_eu_member' => false,
    ],
    [
        'id' => 26,
        'short_name' => 'BL',
        'name' => 'Saint Barthélemy',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 27,
        'short_name' => 'BM',
        'name' => 'Bermuda',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 28,
        'short_name' => 'BN',
        'name' => 'Brunei Darussalam',
        'phonecode' => '673',
        'is_eu_member' => false,
    ],
    [
        'id' => 29,
        'short_name' => 'BO',
        'name' => 'Bolivia, Plurinational State of',
        'phonecode' => '591',
        'is_eu_member' => false,
    ],
    [
        'id' => 30,
        'short_name' => 'BQ',
        'name' => 'Bonaire, Sint Eustatius and Saba',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 31,
        'short_name' => 'BR',
        'name' => 'Brazil',
        'phonecode' => '55',
        'is_eu_member' => false,
    ],
    [
        'id' => 32,
        'short_name' => 'BS',
        'name' => 'Bahamas',
        'phonecode' => '1-242',
        'is_eu_member' => false,
    ],
    [
        'id' => 33,
        'short_name' => 'BT',
        'name' => 'Bhutan',
        'phonecode' => '975',
        'is_eu_member' => false,
    ],
    [
        'id' => 34,
        'short_name' => 'BV',
        'name' => 'Bouvet Island',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 35,
        'short_name' => 'BW',
        'name' => 'Botswana',
        'phonecode' => '267',
        'is_eu_member' => false,
    ],
    [
        'id' => 36,
        'short_name' => 'BY',
        'name' => 'Belarus',
        'phonecode' => '375',
        'is_eu_member' => false,
    ],
    [
        'id' => 37,
        'short_name' => 'BZ',
        'name' => 'Belize',
        'phonecode' => '501',
        'is_eu_member' => false,
    ],
    [
        'id' => 38,
        'short_name' => 'CA',
        'name' => 'Canada',
        'phonecode' => '1',
        'is_eu_member' => false,
    ],
    [
        'id' => 39,
        'short_name' => 'CC',
        'name' => 'Cocos (Keeling) Islands',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 40,
        'short_name' => 'CD',
        'name' => 'Congo, The Democratic Republic of the',
        'phonecode' => '243',
        'is_eu_member' => false,
    ],
    [
        'id' => 41,
        'short_name' => 'CF',
        'name' => 'Central African Republic',
        'phonecode' => '236',
        'is_eu_member' => false,
    ],
    [
        'id' => 42,
        'short_name' => 'CG',
        'name' => 'Congo',
        'phonecode' => '242',
        'is_eu_member' => false,
    ],
    [
        'id' => 43,
        'short_name' => 'CH',
        'name' => 'Switzerland',
        'phonecode' => '41',
        'is_eu_member' => false,
    ],
    [
        'id' => 44,
        'short_name' => 'CI',
        'name' => 'Côte d\'Ivoire',
        'phonecode' => '225',
        'is_eu_member' => false,
    ],
    [
        'id' => 45,
        'short_name' => 'CK',
        'name' => 'Cook Islands',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 46,
        'short_name' => 'CL',
        'name' => 'Chile',
        'phonecode' => '56',
        'is_eu_member' => false,
    ],
    [
        'id' => 47,
        'short_name' => 'CM',
        'name' => 'Cameroon',
        'phonecode' => '237',
        'is_eu_member' => false,
    ],
    [
        'id' => 48,
        'short_name' => 'CN',
        'name' => 'China',
        'phonecode' => '86',
        'is_eu_member' => false,
    ],
    [
        'id' => 49,
        'short_name' => 'CO',
        'name' => 'Colombia',
        'phonecode' => '57',
        'is_eu_member' => false,
    ],
    [
        'id' => 50,
        'short_name' => 'CR',
        'name' => 'Costa Rica',
        'phonecode' => '506',
        'is_eu_member' => false,
    ],
    [
        'id' => 51,
        'short_name' => 'CU',
        'name' => 'Cuba',
        'phonecode' => '53',
        'is_eu_member' => false,
    ],
    [
        'id' => 52,
        'short_name' => 'CV',
        'name' => 'Cabo Verde',
        'phonecode' => '238',
        'is_eu_member' => false,
    ],
    [
        'id' => 53,
        'short_name' => 'CW',
        'name' => 'Curaçao',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 54,
        'short_name' => 'CX',
        'name' => 'Christmas Island',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 55,
        'short_name' => 'CY',
        'name' => 'Cyprus',
        'phonecode' => '357',
        'is_eu_member' => true,
    ],
    [
        'id' => 56,
        'short_name' => 'CZ',
        'name' => 'Czechia',
        'phonecode' => '420',
        'is_eu_member' => true,
    ],
    [
        'id' => 57,
        'short_name' => 'DE',
        'name' => 'Germany',
        'phonecode' => '49',
        'is_eu_member' => true,
    ],
    [
        'id' => 58,
        'short_name' => 'DJ',
        'name' => 'Djibouti',
        'phonecode' => '253',
        'is_eu_member' => false,
    ],
    [
        'id' => 59,
        'short_name' => 'DK',
        'name' => 'Denmark',
        'phonecode' => '45',
        'is_eu_member' => true,
    ],
    [
        'id' => 60,
        'short_name' => 'DM',
        'name' => 'Dominica',
        'phonecode' => '1-767',
        'is_eu_member' => false,
    ],
    [
        'id' => 61,
        'short_name' => 'DO',
        'name' => 'Dominican Republic',
        'phonecode' => '1-809',
        'is_eu_member' => false,
    ],
    [
        'id' => 62,
        'short_name' => 'DZ',
        'name' => 'Algeria',
        'phonecode' => '213',
        'is_eu_member' => false,
    ],
    [
        'id' => 63,
        'short_name' => 'EC',
        'name' => 'Ecuador',
        'phonecode' => '593',
        'is_eu_member' => false,
    ],
    [
        'id' => 64,
        'short_name' => 'EE',
        'name' => 'Estonia',
        'phonecode' => '372',
        'is_eu_member' => true,
    ],
    [
        'id' => 65,
        'short_name' => 'EG',
        'name' => 'Egypt',
        'phonecode' => '20',
        'is_eu_member' => false,
    ],
    [
        'id' => 66,
        'short_name' => 'EH',
        'name' => 'Western Sahara',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 67,
        'short_name' => 'ER',
        'name' => 'Eritrea',
        'phonecode' => '291',
        'is_eu_member' => false,
    ],
    [
        'id' => 68,
        'short_name' => 'ES',
        'name' => 'Spain',
        'phonecode' => '34',
        'is_eu_member' => true,
    ],
    [
        'id' => 69,
        'short_name' => 'ET',
        'name' => 'Ethiopia',
        'phonecode' => '251',
        'is_eu_member' => false,
    ],
    [
        'id' => 70,
        'short_name' => 'FI',
        'name' => 'Finland',
        'phonecode' => '358',
        'is_eu_member' => true,
    ],
    [
        'id' => 71,
        'short_name' => 'FJ',
        'name' => 'Fiji',
        'phonecode' => '679',
        'is_eu_member' => false,
    ],
    [
        'id' => 72,
        'short_name' => 'FK',
        'name' => 'Falkland Islands (Malvinas)',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 73,
        'short_name' => 'FM',
        'name' => 'Micronesia, Federated States of',
        'phonecode' => '691',
        'is_eu_member' => false,
    ],
    [
        'id' => 74,
        'short_name' => 'FO',
        'name' => 'Faroe Islands',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 75,
        'short_name' => 'FR',
        'name' => 'France',
        'phonecode' => '33',
        'is_eu_member' => true,
    ],
    [
        'id' => 76,
        'short_name' => 'GA',
        'name' => 'Gabon',
        'phonecode' => '241',
        'is_eu_member' => false,
    ],
    [
        'id' => 77,
        'short_name' => 'GB',
        'name' => 'United Kingdom',
        'phonecode' => '44',
        'is_eu_member' => false,
    ],
    [
        'id' => 78,
        'short_name' => 'GD',
        'name' => 'Grenada',
        'phonecode' => '1-473',
        'is_eu_member' => false,
    ],
    [
        'id' => 79,
        'short_name' => 'GE',
        'name' => 'Georgia',
        'phonecode' => '995',
        'is_eu_member' => false,
    ],
    [
        'id' => 80,
        'short_name' => 'GF',
        'name' => 'French Guiana',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 81,
        'short_name' => 'GG',
        'name' => 'Guernsey',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 82,
        'short_name' => 'GH',
        'name' => 'Ghana',
        'phonecode' => '233',
        'is_eu_member' => false,
    ],
    [
        'id' => 83,
        'short_name' => 'GI',
        'name' => 'Gibraltar',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 84,
        'short_name' => 'GL',
        'name' => 'Greenland',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 85,
        'short_name' => 'GM',
        'name' => 'Gambia',
        'phonecode' => '220',
        'is_eu_member' => false,
    ],
    [
        'id' => 86,
        'short_name' => 'GN',
        'name' => 'Guinea',
        'phonecode' => '224',
        'is_eu_member' => false,
    ],
    [
        'id' => 87,
        'short_name' => 'GP',
        'name' => 'Guadeloupe',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 88,
        'short_name' => 'GQ',
        'name' => 'Equatorial Guinea',
        'phonecode' => '240',
        'is_eu_member' => false,
    ],
    [
        'id' => 89,
        'short_name' => 'GR',
        'name' => 'Greece',
        'phonecode' => '30',
        'is_eu_member' => true,
    ],
    [
        'id' => 90,
        'short_name' => 'GS',
        'name' => 'South Georgia and the South Sandwich Islands',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 91,
        'short_name' => 'GT',
        'name' => 'Guatemala',
        'phonecode' => '502',
        'is_eu_member' => false,
    ],
    [
        'id' => 92,
        'short_name' => 'GU',
        'name' => 'Guam',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 93,
        'short_name' => 'GW',
        'name' => 'Guinea-Bissau',
        'phonecode' => '245',
        'is_eu_member' => false,
    ],
    [
        'id' => 94,
        'short_name' => 'GY',
        'name' => 'Guyana',
        'phonecode' => '592',
        'is_eu_member' => false,
    ],
    [
        'id' => 95,
        'short_name' => 'HK',
        'name' => 'Hong Kong',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 96,
        'short_name' => 'HM',
        'name' => 'Heard Island and McDonald Islands',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 97,
        'short_name' => 'HN',
        'name' => 'Honduras',
        'phonecode' => '504',
        'is_eu_member' => false,
    ],
    [
        'id' => 98,
        'short_name' => 'HR',
        'name' => 'Croatia',
        'phonecode' => '385',
        'is_eu_member' => true,
    ],
    [
        'id' => 99,
        'short_name' => 'HT',
        'name' => 'Haiti',
        'phonecode' => '509',
        'is_eu_member' => false,
    ],
    [
        'id' => 100,
        'short_name' => 'HU',
        'name' => 'Hungary',
        'phonecode' => '36',
        'is_eu_member' => true,
    ],
    [
        'id' => 101,
        'short_name' => 'ID',
        'name' => 'Indonesia',
        'phonecode' => '62',
        'is_eu_member' => false,
    ],
    [
        'id' => 102,
        'short_name' => 'IE',
        'name' => 'Ireland',
        'phonecode' => '353',
        'is_eu_member' => true,
    ],
    [
        'id' => 103,
        'short_name' => 'IL',
        'name' => 'Israel',
        'phonecode' => '972',
        'is_eu_member' => false,
    ],
    [
        'id' => 104,
        'short_name' => 'IM',
        'name' => 'Isle of Man',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 105,
        'short_name' => 'IN',
        'name' => 'India',
        'phonecode' => '91',
        'is_eu_member' => false,
    ],
    [
        'id' => 106,
        'short_name' => 'IO',
        'name' => 'British Indian Ocean Territory',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 107,
        'short_name' => 'IQ',
        'name' => 'Iraq',
        'phonecode' => '964',
        'is_eu_member' => false,
    ],
    [
        'id' => 108,
        'short_name' => 'IR',
        'name' => 'Iran, Islamic Republic of',
        'phonecode' => '98',
        'is_eu_member' => false,
    ],
    [
        'id' => 109,
        'short_name' => 'IS',
        'name' => 'Iceland',
        'phonecode' => '354',
        'is_eu_member' => false,
    ],
    [
        'id' => 110,
        'short_name' => 'IT',
        'name' => 'Italy',
        'phonecode' => '39',
        'is_eu_member' => true,
    ],
    [
        'id' => 111,
        'short_name' => 'JE',
        'name' => 'Jersey',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 112,
        'short_name' => 'JM',
        'name' => 'Jamaica',
        'phonecode' => '1-876',
        'is_eu_member' => false,
    ],
    [
        'id' => 113,
        'short_name' => 'JO',
        'name' => 'Jordan',
        'phonecode' => '962',
        'is_eu_member' => false,
    ],
    [
        'id' => 114,
        'short_name' => 'JP',
        'name' => 'Japan',
        'phonecode' => '81',
        'is_eu_member' => false,
    ],
    [
        'id' => 115,
        'short_name' => 'KE',
        'name' => 'Kenya',
        'phonecode' => '254',
        'is_eu_member' => false,
    ],
    [
        'id' => 116,
        'short_name' => 'KG',
        'name' => 'Kyrgyzstan',
        'phonecode' => '996',
        'is_eu_member' => false,
    ],
    [
        'id' => 117,
        'short_name' => 'KH',
        'name' => 'Cambodia',
        'phonecode' => '855',
        'is_eu_member' => false,
    ],
    [
        'id' => 118,
        'short_name' => 'KI',
        'name' => 'Kiribati',
        'phonecode' => '686',
        'is_eu_member' => false,
    ],
    [
        'id' => 119,
        'short_name' => 'KM',
        'name' => 'Comoros',
        'phonecode' => '269',
        'is_eu_member' => false,
    ],
    [
        'id' => 120,
        'short_name' => 'KN',
        'name' => 'Saint Kitts and Nevis',
        'phonecode' => '1-869',
        'is_eu_member' => false,
    ],
    [
        'id' => 121,
        'short_name' => 'KP',
        'name' => 'Korea, Democratic People\'s Republic of',
        'phonecode' => '850',
        'is_eu_member' => false,
    ],
    [
        'id' => 122,
        'short_name' => 'KR',
        'name' => 'Korea, Republic of',
        'phonecode' => '82',
        'is_eu_member' => false,
    ],
    [
        'id' => 123,
        'short_name' => 'KW',
        'name' => 'Kuwait',
        'phonecode' => '965',
        'is_eu_member' => false,
    ],
    [
        'id' => 124,
        'short_name' => 'KY',
        'name' => 'Cayman Islands',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 125,
        'short_name' => 'KZ',
        'name' => 'Kazakhstan',
        'phonecode' => '7',
        'is_eu_member' => false,
    ],
    [
        'id' => 126,
        'short_name' => 'LA',
        'name' => 'Lao People\'s Democratic Republic',
        'phonecode' => '856',
        'is_eu_member' => false,
    ],
    [
        'id' => 127,
        'short_name' => 'LB',
        'name' => 'Lebanon',
        'phonecode' => '961',
        'is_eu_member' => false,
    ],
    [
        'id' => 128,
        'short_name' => 'LC',
        'name' => 'Saint Lucia',
        'phonecode' => '1-758',
        'is_eu_member' => false,
    ],
    [
        'id' => 129,
        'short_name' => 'LI',
        'name' => 'Liechtenstein',
        'phonecode' => '423',
        'is_eu_member' => false,
    ],
    [
        'id' => 130,
        'short_name' => 'LK',
        'name' => 'Sri Lanka',
        'phonecode' => '94',
        'is_eu_member' => false,
    ],
    [
        'id' => 131,
        'short_name' => 'LR',
        'name' => 'Liberia',
        'phonecode' => '231',
        'is_eu_member' => false,
    ],
    [
        'id' => 132,
        'short_name' => 'LS',
        'name' => 'Lesotho',
        'phonecode' => '266',
        'is_eu_member' => false,
    ],
    [
        'id' => 133,
        'short_name' => 'LT',
        'name' => 'Lithuania',
        'phonecode' => '370',
        'is_eu_member' => true,
    ],
    [
        'id' => 134,
        'short_name' => 'LU',
        'name' => 'Luxembourg',
        'phonecode' => '352',
        'is_eu_member' => true,
    ],
    [
        'id' => 135,
        'short_name' => 'LV',
        'name' => 'Latvia',
        'phonecode' => '371',
        'is_eu_member' => true,
    ],
    [
        'id' => 136,
        'short_name' => 'LY',
        'name' => 'Libya',
        'phonecode' => '218',
        'is_eu_member' => false,
    ],
    [
        'id' => 137,
        'short_name' => 'MA',
        'name' => 'Morocco',
        'phonecode' => '212',
        'is_eu_member' => false,
    ],
    [
        'id' => 138,
        'short_name' => 'MC',
        'name' => 'Monaco',
        'phonecode' => '377',
        'is_eu_member' => false,
    ],
    [
        'id' => 139,
        'short_name' => 'MD',
        'name' => 'Moldova, Republic of',
        'phonecode' => '373',
        'is_eu_member' => false,
    ],
    [
        'id' => 140,
        'short_name' => 'ME',
        'name' => 'Montenegro',
        'phonecode' => '382',
        'is_eu_member' => false,
    ],
    [
        'id' => 141,
        'short_name' => 'MF',
        'name' => 'Saint Martin (French part)',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 142,
        'short_name' => 'MG',
        'name' => 'Madagascar',
        'phonecode' => '261',
        'is_eu_member' => false,
    ],
    [
        'id' => 143,
        'short_name' => 'MH',
        'name' => 'Marshall Islands',
        'phonecode' => '692',
        'is_eu_member' => false,
    ],
    [
        'id' => 144,
        'short_name' => 'MK',
        'name' => 'North Macedonia',
        'phonecode' => '389',
        'is_eu_member' => false,
    ],
    [
        'id' => 145,
        'short_name' => 'ML',
        'name' => 'Mali',
        'phonecode' => '223',
        'is_eu_member' => false,
    ],
    [
        'id' => 146,
        'short_name' => 'MM',
        'name' => 'Myanmar',
        'phonecode' => '95',
        'is_eu_member' => false,
    ],
    [
        'id' => 147,
        'short_name' => 'MN',
        'name' => 'Mongolia',
        'phonecode' => '976',
        'is_eu_member' => false,
    ],
    [
        'id' => 148,
        'short_name' => 'MO',
        'name' => 'Macao',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 149,
        'short_name' => 'MP',
        'name' => 'Northern Mariana Islands',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 150,
        'short_name' => 'MQ',
        'name' => 'Martinique',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 151,
        'short_name' => 'MR',
        'name' => 'Mauritania',
        'phonecode' => '222',
        'is_eu_member' => false,
    ],
    [
        'id' => 152,
        'short_name' => 'MS',
        'name' => 'Montserrat',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 153,
        'short_name' => 'MT',
        'name' => 'Malta',
        'phonecode' => '356',
        'is_eu_member' => true,
    ],
    [
        'id' => 154,
        'short_name' => 'MU',
        'name' => 'Mauritius',
        'phonecode' => '230',
        'is_eu_member' => false,
    ],
    [
        'id' => 155,
        'short_name' => 'MV',
        'name' => 'Maldives',
        'phonecode' => '960',
        'is_eu_member' => false,
    ],
    [
        'id' => 156,
        'short_name' => 'MW',
        'name' => 'Malawi',
        'phonecode' => '265',
        'is_eu_member' => false,
    ],
    [
        'id' => 157,
        'short_name' => 'MX',
        'name' => 'Mexico',
        'phonecode' => '52',
        'is_eu_member' => false,
    ],
    [
        'id' => 158,
        'short_name' => 'MY',
        'name' => 'Malaysia',
        'phonecode' => '60',
        'is_eu_member' => false,
    ],
    [
        'id' => 159,
        'short_name' => 'MZ',
        'name' => 'Mozambique',
        'phonecode' => '258',
        'is_eu_member' => false,
    ],
    [
        'id' => 160,
        'short_name' => 'NA',
        'name' => 'Namibia',
        'phonecode' => '264',
        'is_eu_member' => false,
    ],
    [
        'id' => 161,
        'short_name' => 'NC',
        'name' => 'New Caledonia',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 162,
        'short_name' => 'NE',
        'name' => 'Niger',
        'phonecode' => '227',
        'is_eu_member' => false,
    ],
    [
        'id' => 163,
        'short_name' => 'NF',
        'name' => 'Norfolk Island',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 164,
        'short_name' => 'NG',
        'name' => 'Nigeria',
        'phonecode' => '234',
        'is_eu_member' => false,
    ],
    [
        'id' => 165,
        'short_name' => 'NI',
        'name' => 'Nicaragua',
        'phonecode' => '505',
        'is_eu_member' => false,
    ],
    [
        'id' => 166,
        'short_name' => 'NL',
        'name' => 'Netherlands',
        'phonecode' => '31',
        'is_eu_member' => true,
    ],
    [
        'id' => 167,
        'short_name' => 'NO',
        'name' => 'Norway',
        'phonecode' => '47',
        'is_eu_member' => false,
    ],
    [
        'id' => 168,
        'short_name' => 'NP',
        'name' => 'Nepal',
        'phonecode' => '977',
        'is_eu_member' => false,
    ],
    [
        'id' => 169,
        'short_name' => 'NR',
        'name' => 'Nauru',
        'phonecode' => '674',
        'is_eu_member' => false,
    ],
    [
        'id' => 170,
        'short_name' => 'NU',
        'name' => 'Niue',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 171,
        'short_name' => 'NZ',
        'name' => 'New Zealand',
        'phonecode' => '64',
        'is_eu_member' => false,
    ],
    [
        'id' => 172,
        'short_name' => 'OM',
        'name' => 'Oman',
        'phonecode' => '968',
        'is_eu_member' => false,
    ],
    [
        'id' => 173,
        'short_name' => 'PA',
        'name' => 'Panama',
        'phonecode' => '507',
        'is_eu_member' => false,
    ],
    [
        'id' => 174,
        'short_name' => 'PE',
        'name' => 'Peru',
        'phonecode' => '51',
        'is_eu_member' => false,
    ],
    [
        'id' => 175,
        'short_name' => 'PF',
        'name' => 'French Polynesia',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 176,
        'short_name' => 'PG',
        'name' => 'Papua New Guinea',
        'phonecode' => '675',
        'is_eu_member' => false,
    ],
    [
        'id' => 177,
        'short_name' => 'PH',
        'name' => 'Philippines',
        'phonecode' => '63',
        'is_eu_member' => false,
    ],
    [
        'id' => 178,
        'short_name' => 'PK',
        'name' => 'Pakistan',
        'phonecode' => '92',
        'is_eu_member' => false,
    ],
    [
        'id' => 179,
        'short_name' => 'PL',
        'name' => 'Poland',
        'phonecode' => '48',
        'is_eu_member' => true,
    ],
    [
        'id' => 180,
        'short_name' => 'PM',
        'name' => 'Saint Pierre and Miquelon',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 181,
        'short_name' => 'PN',
        'name' => 'Pitcairn',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 182,
        'short_name' => 'PR',
        'name' => 'Puerto Rico',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 183,
        'short_name' => 'PS',
        'name' => 'Palestine, State of',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 184,
        'short_name' => 'PT',
        'name' => 'Portugal',
        'phonecode' => '351',
        'is_eu_member' => true,
    ],
    [
        'id' => 185,
        'short_name' => 'PW',
        'name' => 'Palau',
        'phonecode' => '680',
        'is_eu_member' => false,
    ],
    [
        'id' => 186,
        'short_name' => 'PY',
        'name' => 'Paraguay',
        'phonecode' => '595',
        'is_eu_member' => false,
    ],
    [
        'id' => 187,
        'short_name' => 'QA',
        'name' => 'Qatar',
        'phonecode' => '974',
        'is_eu_member' => false,
    ],
    [
        'id' => 188,
        'short_name' => 'RE',
        'name' => 'Réunion',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 189,
        'short_name' => 'RO',
        'name' => 'Romania',
        'phonecode' => '40',
        'is_eu_member' => true,
    ],
    [
        'id' => 190,
        'short_name' => 'RS',
        'name' => 'Serbia',
        'phonecode' => '381',
        'is_eu_member' => false,
    ],
    [
        'id' => 191,
        'short_name' => 'RU',
        'name' => 'Russian Federation',
        'phonecode' => '7',
        'is_eu_member' => false,
    ],
    [
        'id' => 192,
        'short_name' => 'RW',
        'name' => 'Rwanda',
        'phonecode' => '250',
        'is_eu_member' => false,
    ],
    [
        'id' => 193,
        'short_name' => 'SA',
        'name' => 'Saudi Arabia',
        'phonecode' => '966',
        'is_eu_member' => false,
    ],
    [
        'id' => 194,
        'short_name' => 'SB',
        'name' => 'Solomon Islands',
        'phonecode' => '677',
        'is_eu_member' => false,
    ],
    [
        'id' => 195,
        'short_name' => 'SC',
        'name' => 'Seychelles',
        'phonecode' => '248',
        'is_eu_member' => false,
    ],
    [
        'id' => 196,
        'short_name' => 'SD',
        'name' => 'Sudan',
        'phonecode' => '249',
        'is_eu_member' => false,
    ],
    [
        'id' => 197,
        'short_name' => 'SE',
        'name' => 'Sweden',
        'phonecode' => '46',
        'is_eu_member' => true,
    ],
    [
        'id' => 198,
        'short_name' => 'SG',
        'name' => 'Singapore',
        'phonecode' => '65',
        'is_eu_member' => false,
    ],
    [
        'id' => 199,
        'short_name' => 'SH',
        'name' => 'Saint Helena, Ascension and Tristan da Cunha',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 200,
        'short_name' => 'SI',
        'name' => 'Slovenia',
        'phonecode' => '386',
        'is_eu_member' => true,
    ],
    [
        'id' => 201,
        'short_name' => 'SJ',
        'name' => 'Svalbard and Jan Mayen',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 202,
        'short_name' => 'SK',
        'name' => 'Slovakia',
        'phonecode' => '421',
        'is_eu_member' => true,
    ],
    [
        'id' => 203,
        'short_name' => 'SL',
        'name' => 'Sierra Leone',
        'phonecode' => '232',
        'is_eu_member' => false,
    ],
    [
        'id' => 204,
        'short_name' => 'SM',
        'name' => 'San Marino',
        'phonecode' => '378',
        'is_eu_member' => false,
    ],
    [
        'id' => 205,
        'short_name' => 'SN',
        'name' => 'Senegal',
        'phonecode' => '221',
        'is_eu_member' => false,
    ],
    [
        'id' => 206,
        'short_name' => 'SO',
        'name' => 'Somalia',
        'phonecode' => '252',
        'is_eu_member' => false,
    ],
    [
        'id' => 207,
        'short_name' => 'SR',
        'name' => 'Suriname',
        'phonecode' => '597',
        'is_eu_member' => false,
    ],
    [
        'id' => 208,
        'short_name' => 'SS',
        'name' => 'South Sudan',
        'phonecode' => '211',
        'is_eu_member' => false,
    ],
    [
        'id' => 209,
        'short_name' => 'ST',
        'name' => 'Sao Tome and Principe',
        'phonecode' => '239',
        'is_eu_member' => false,
    ],
    [
        'id' => 210,
        'short_name' => 'SV',
        'name' => 'El Salvador',
        'phonecode' => '503',
        'is_eu_member' => false,
    ],
    [
        'id' => 211,
        'short_name' => 'SX',
        'name' => 'Sint Maarten (Dutch part)',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 212,
        'short_name' => 'SY',
        'name' => 'Syrian Arab Republic',
        'phonecode' => '963',
        'is_eu_member' => false,
    ],
    [
        'id' => 213,
        'short_name' => 'SZ',
        'name' => 'Eswatini',
        'phonecode' => '268',
        'is_eu_member' => false,
    ],
    [
        'id' => 214,
        'short_name' => 'TC',
        'name' => 'Turks and Caicos Islands',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 215,
        'short_name' => 'TD',
        'name' => 'Chad',
        'phonecode' => '235',
        'is_eu_member' => false,
    ],
    [
        'id' => 216,
        'short_name' => 'TF',
        'name' => 'French Southern Territories',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 217,
        'short_name' => 'TG',
        'name' => 'Togo',
        'phonecode' => '228',
        'is_eu_member' => false,
    ],
    [
        'id' => 218,
        'short_name' => 'TH',
        'name' => 'Thailand',
        'phonecode' => '66',
        'is_eu_member' => false,
    ],
    [
        'id' => 219,
        'short_name' => 'TJ',
        'name' => 'Tajikistan',
        'phonecode' => '992',
        'is_eu_member' => false,
    ],
    [
        'id' => 220,
        'short_name' => 'TK',
        'name' => 'Tokelau',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 221,
        'short_name' => 'TL',
        'name' => 'Timor-Leste',
        'phonecode' => '670',
        'is_eu_member' => false,
    ],
    [
        'id' => 222,
        'short_name' => 'TM',
        'name' => 'Turkmenistan',
        'phonecode' => '993',
        'is_eu_member' => false,
    ],
    [
        'id' => 223,
        'short_name' => 'TN',
        'name' => 'Tunisia',
        'phonecode' => '216',
        'is_eu_member' => false,
    ],
    [
        'id' => 224,
        'short_name' => 'TO',
        'name' => 'Tonga',
        'phonecode' => '676',
        'is_eu_member' => false,
    ],
    [
        'id' => 225,
        'short_name' => 'TR',
        'name' => 'Turkey',
        'phonecode' => '90',
        'is_eu_member' => false,
    ],
    [
        'id' => 226,
        'short_name' => 'TT',
        'name' => 'Trinidad and Tobago',
        'phonecode' => '1-868',
        'is_eu_member' => false,
    ],
    [
        'id' => 227,
        'short_name' => 'TV',
        'name' => 'Tuvalu',
        'phonecode' => '688',
        'is_eu_member' => false,
    ],
    [
        'id' => 228,
        'short_name' => 'TW',
        'name' => 'Taiwan, Province of China',
        'phonecode' => '886',
        'is_eu_member' => false,
    ],
    [
        'id' => 229,
        'short_name' => 'TZ',
        'name' => 'Tanzania, United Republic of',
        'phonecode' => '255',
        'is_eu_member' => false,
    ],
    [
        'id' => 230,
        'short_name' => 'UA',
        'name' => 'Ukraine',
        'phonecode' => '380',
        'is_eu_member' => false,
    ],
    [
        'id' => 231,
        'short_name' => 'UG',
        'name' => 'Uganda',
        'phonecode' => '256',
        'is_eu_member' => false,
    ],
    [
        'id' => 232,
        'short_name' => 'UM',
        'name' => 'United States Minor Outlying Islands',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 233,
        'short_name' => 'US',
        'name' => 'United States',
        'phonecode' => '1',
        'is_eu_member' => false,
    ],
    [
        'id' => 234,
        'short_name' => 'UY',
        'name' => 'Uruguay',
        'phonecode' => '598',
        'is_eu_member' => false,
    ],
    [
        'id' => 235,
        'short_name' => 'UZ',
        'name' => 'Uzbekistan',
        'phonecode' => '998',
        'is_eu_member' => false,
    ],
    [
        'id' => 236,
        'short_name' => 'VA',
        'name' => 'Holy See (Vatican City State)',
        'phonecode' => '379',
        'is_eu_member' => false,
    ],
    [
        'id' => 237,
        'short_name' => 'VC',
        'name' => 'Saint Vincent and the Grenadines',
        'phonecode' => '1-784',
        'is_eu_member' => false,
    ],
    [
        'id' => 238,
        'short_name' => 'VE',
        'name' => 'Venezuela, Bolivarian Republic of',
        'phonecode' => '58',
        'is_eu_member' => false,
    ],
    [
        'id' => 239,
        'short_name' => 'VG',
        'name' => 'Virgin Islands, British',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 240,
        'short_name' => 'VI',
        'name' => 'Virgin Islands, U.S.',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 241,
        'short_name' => 'VN',
        'name' => 'Viet Nam',
        'phonecode' => '84',
        'is_eu_member' => false,
    ],
    [
        'id' => 242,
        'short_name' => 'VU',
        'name' => 'Vanuatu',
        'phonecode' => '678',
        'is_eu_member' => false,
    ],
    [
        'id' => 243,
        'short_name' => 'WF',
        'name' => 'Wallis and Futuna',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 244,
        'short_name' => 'WS',
        'name' => 'Samoa',
        'phonecode' => '685',
        'is_eu_member' => false,
    ],
    [
        'id' => 245,
        'short_name' => 'YE',
        'name' => 'Yemen',
        'phonecode' => '967',
        'is_eu_member' => false,
    ],
    [
        'id' => 246,
        'short_name' => 'YT',
        'name' => 'Mayotte',
        'phonecode' => null,
        'is_eu_member' => false,
    ],
    [
        'id' => 247,
        'short_name' => 'ZA',
        'name' => 'South Africa',
        'phonecode' => '27',
        'is_eu_member' => false,
    ],
    [
        'id' => 248,
        'short_name' => 'ZM',
        'name' => 'Zambia',
        'phonecode' => '260',
        'is_eu_member' => false,
    ],
    [
        'id' => 249,
        'short_name' => 'ZW',
        'name' => 'Zimbabwe',
        'phonecode' => '263',
        'is_eu_member' => false,
    ],
];